### ISSUE TITLE
Tracer 1.7.1 does ont open outfiles of G-Phocs

### ISSUE THREAD

**Issue by gscabanne** [beast-dev/tracer#153]
Hi, we have realized that ver 1.7 does not open outfiles of G-Phocs, a software to estimate population genetic parameters with genomics data-sets
Gphocs web is>http://compgen.cshl.edu/GPhoCS/

Previous versions of Tracer (i.e., 1.5 and 1.6) do open the outfiles. This has been consisten across different outfiles and platforms. 

What happenes is a) the outfiles have two blank spaces instead of one space separating the last two columns of data. Changing two to one space helped to al least open the file, but Tracer was not able to properly read the parameters, and presented very weird tracer graphs. I was ont able to figure out what is the cause of the problem. So, I am using now  Tracer 1.6 or 1.5 and there not any problem to open these outfiles. Apparently, there has been a change from ver 1.6 to 1.7 that precluded Tracer to open G-Phocs outfiles
Did anyone else experience this issue?

Best

**Comment by MarineBio5** [comment]
Hi, 

I experienced this issue too. For those (like me) who struggled to find an older version it is available here:
https://github.com/beast-dev/tracer/releases/tag/v1.6
Best

**Comment by walterxie** [comment]
Any example files to reproduce this issue?

**Comment by gscabanne** [comment]
Hi, you may try with the attached one. I currently am using version 1.6. This issue is now well known among gphocs users.best
GUSTAVO SEBASTIÁN CABANNE
 Investigador-Researcher
 Museo Arg. de Cs. Naturales
 "Bernardino Rivadavia",
 Buenos Aires, Argentina
 Tel: 54 11 4982 6595 int 186
Associate Editor of Ornithology Research -Springer- (former Revista Brasileira de Ornitología), and Molecular Phylogenetics and Evolution -Elsevier-

http://gscabanne.wixsite.com/science
http://www.conicet.gov.ar/new_scp/detalle.php?keywords=&id=32339&datos_academicos=yes 

    On Thursday, April 29, 2021, 08:38:34 PM GMT-3, Walter ***@***.***> wrote:  
 
 


Any example files to reproduce this issue?

**Comment by walterxie** [comment]
@gscabanne there is no attachment from your previous posts.

**Comment by walterxie** [comment]
It will be appreciated if anyone could provide an example file.

**Comment by gscabanne** [comment]
NOw there is.
GUSTAVO SEBASTIÁN CABANNE
 Investigador-Researcher
 Museo Arg. de Cs. Naturales
 "Bernardino Rivadavia",
 Buenos Aires, Argentina
 Tel: 54 11 4982 6595 int 186
Associate Editor of Ornithology Research -Springer- (former Revista Brasileira de Ornitología), and Molecular Phylogenetics and Evolution -Elsevier-

http://gscabanne.wixsite.com/science
http://www.conicet.gov.ar/new_scp/detalle.php?keywords=&id=32339&datos_academicos=yes 

    On Friday, April 30, 2021, 01:19:16 AM GMT-3, Walter ***@***.***> wrote:  
 
 


@gscabanne there is no attachment from your previous posts.

**Comment by FatihSarigol** [comment]
[mcmc-trace_1.log](https://github.com/beast-dev/tracer/files/6995945/mcmc-trace_1.log)
Hi, old post, but I dont see a file in the last post so I attach mine.. 
So I am using 1.6 version fine, but wanted to try 1.7 because Demographic Reconstruction analysis doesn't respond on 1.6 for this file again from Gphocs, so that can be another issue to report here. Yeah so 1.7 doesnt open this file.
thanks

**Comment by walterxie** [comment]
Hi @FatihSarigol, thank you very much to provide the example log file. There are 2 problems in this log file:

1. The empty column was added at the last 3rd column. The screen shot is attached. After I read Gphocs manual https://raw.githubusercontent.com/gphocs-dev/G-PhoCS/master/GPhoCS_Manual.pdf, and I think it is a bug of Gphocs. Tracer parser will ignore the empty column, as long as the header (parameter names) is in a correct format, such as the log file you provided. But since Tracer 1.7, we added a validation method after loading, which was using a different code to read, so this empty column made Tracer crashed. 
I have updated that code to use the same parsing process, which will handle this matter. 

2. An extra white space is added to the values. I did not check all columns, but at least `theta_NORWAY` column. I am not sure if it was done for any other purposes, but it looks unnecessary and problematic. 
So I add a trim method to remove any leading and trailing white space from the value string.
 
![Screenshot from 2021-08-17 14-35-10](https://user-images.githubusercontent.com/5743014/129667138-f7e7d645-3647-4773-b35b-2dc540167c3f.png)

**Comment by walterxie** [comment]
You log file works in the latest code. The bug-fix will be available in the next release. Alternatively, you can build the jar using the latest code in the repository. 
I will leave this issue open for several days.

**Comment by FatihSarigol** [comment]
Hey Walter,
Thank you for checking and figuring out the tiny issue!
Before going for building the new jar, I wanted to try to fix the problems you pointed out in Gphocs' output file. 

This code below did the job, which fixes both of the problems, it removes those spaces in front of the values and fixes the field shift issue in the header as well (I write it here in case anyone else would find this post before the new release) :

`awk -v OFS="\t" '$1=$1' mcmc-trace_1.log` > [fixed.log](https://github.com/beast-dev/tracer/files/7003832/fixed.log)

and so it now opens with version `1.7.2`

Can I ask another question here, Walter; should I be able to run `Demographic Reconstruction` or any of the other analyses with this file or am I missing something? Such as do I need a specific trace log for `Population Size` or does it work from any of the samples I already have in the file? Because for me none of the analyses work really.

Thanks a lot!

**Comment by walterxie** [comment]
Hi Fatih, we cannot control the behavior and output of other software. There is already a warning message in the GUI panel:

![Screenshot from 2021-08-19 10-32-17](https://user-images.githubusercontent.com/5743014/129981040-3df14e89-fa2d-4e21-9d98-feaa13367d88.png)

Personally, I suggest you to use BEAST or [LPhy](https://linguaphylo.github.io/).
