### ISSUE TITLE
Error in plotting the Bayesian skyline plot

### ISSUE THREAD

**Issue by cinthylorein** [beast-dev/tracer#168]
I am not able to plot the skyline plot; while plotting the Bayesian skyline plot, I get an error - 'Fatal exception during plot: null' or 'Fatal exception during initializing group size 10'.  I am logging each 40000 in the log file vs logEvery="400000" in the trees file.  could it be the problem?

**Comment by walterxie** [comment]
Hi Cinthy, as I have mentioned you, the problem was that the state numbers in both log and tree log are not matching. You can either change both logEvery into the same frequency, or resample the log file to 400000 which is same as the tree log. 

But Tracer's error message was confusing. And no validation to check if the number of samples in the log is greater than trees, which is your case. I have added a new Exception to handle the scenarios.

**Comment by walterxie** [comment]
Both incorrect and correct logs are tested

**Comment by cinthylorein** [comment]
Hi Walter, as you mentioned, the issue was the state numbers in both log and tree log did not match exactly.  Thanks for the support.

**Comment by MarcioJRC1** [comment]
Hi Cinthy, how did you fix it exactly?

**Comment by Wanchengshan** [comment]
I also meet the same error "Fatal exception (email the authors): null", and I have double-checked my .log file and .trees file to make sure the counts and the sample ID number of items in both files are the same. Is there any other that I should correct? log file and trees file have been uploaded to the supplement file. Thanks very much!
[37noMono-060524.log](https://github.com/user-attachments/files/15858074/37noMono-060524.log)
[37noMono-060524.trees.log](https://github.com/user-attachments/files/15858081/37noMono-060524.trees.log)
