### ISSUE TITLE
Apply filter option in Analysis menu doesn't seem to work

### ISSUE THREAD

**Issue by rambaut** [beast-dev/tracer#3]
_From @rambaut on July 22, 2016 10:6_

_Copied from original issue: beast-dev/beast-mcmc#828_

**Comment by walterxie** [comment]
@rambaut @alexeid 

I recovered the filter option. The boolean[] filtered in FilteredTraceList is one important flag to apply filtering, and the modified method getValues(int fromIndex, int toIndex, boolean[] filtered)  in Trace ensures the values do not contain filtered data points.

But it seems joint analyses among multiple traces not working after filtering, because the index increase bigger than the sample size after filtering. I will log a separated issue for this.

Cheers,
Walter
