### ISSUE TITLE
Estimates plot when multiple discrete traces are picked is broken

### ISSUE THREAD

**Issue by rambaut** [beast-dev/tracer#4]
_From @rambaut on July 22, 2016 10:2_

Could use circles with area proportional to probability? For ordinal traces, a bar for the mean might be appropriate or mode and CIs? Discrete violin plots?

_Copied from original issue: beast-dev/beast-mcmc#827_

**Comment by walterxie** [comment]
add box plot #61, and use both JIntervalsChart and BoxPlotChart IntervalsPanel. But y axis doe not scale properly for box plot.

**Comment by walterxie** [comment]
Cannot figure out why box plot not working in IntervalsPanel. But I added new chart using different sized triangles to display categorical variables.

![Uploading Screen Shot 2017-04-03 at 3.44.33 pm.png…]()

**Comment by walterxie** [comment]
Receive many criticisms to draw triangles instead of horizontal bars, so change to discrete violin plot:

![screen shot 2017-04-03 at 4 22 23 pm](https://cloud.githubusercontent.com/assets/5743014/24595378/29ab8e52-188a-11e7-8136-0f149977e28a.png)

![screen shot 2017-04-03 at 4 22 34 pm](https://cloud.githubusercontent.com/assets/5743014/24595379/29e5932c-188a-11e7-960e-09c62e4ffb29.png)
